# Generated by Django 5.2.1 on 2025-07-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0004_alter_category_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD $'), ('EUR', 'EUR €'), ('AUD', 'AUD $'), ('GBP', 'GBP £'), ('INR', 'INR ₹'), ('JPY', 'JPY ¥')], default='USD', help_text='Currency for the rate', max_length=3),
        ),
    ]
