# Generated by Django 5.2.1 on 2025-08-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0005_alter_category_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workentry',
            name='folder_name',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
    ]
