# Generated by Django 5.2.1 on 2025-08-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0006_alter_workentry_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workentry',
            name='folder_name',
            field=models.CharField(max_length=100, verbose_name='Folder Name'),
        ),
    ]
