# Generated by Django 5.2.5 on 2025-08-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0007_alter_workentry_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD $'), ('EUR', 'EUR €'), ('GBP', 'GBP £'), ('AUD', 'AUD $')], default='USD', help_text='Currency for the rate', max_length=3),
        ),
    ]
