# Generated by Django 5.2.1 on 2025-09-26 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0009_userloginhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='managed_by',
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
